### ISSUE TITLE
[PE-D][Tester E] No way to filter based on course (and use AggGrade) on them

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T08-4/tp#261] opened 2024-11-08 22:52 UTC
Currently `aggGrade` works on a `filtered list`.
However, there is no way to filter the list based on `course`, which means there is no way to use `aggGrade` for specific courses
![image.png](https://raw.githubusercontent.com/tanwartushar/ped/main/files/dc2be022-9763-4edc-95f6-fad62e04f72c.png)

Hence key aggregate functionalities are missing (which could be expected by the target user of TAHub)
for example: aggregate of midterms of all students taking CS1231S

Possible fixes:

1. add `course` as a parameter in `find` command
2. add `course` as a parameter in `aggGrade` (alongside test name)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: tanwartushar/ped#13

**Comment by Oceankoh** [comment] 2024-11-09 01:52
Hi, thanks for the report. Indeed, we did not account for users who may be TAs of multiple mods when writing the aggGrade function. However, this issue only affects a small minority of users since most TAs only in charge of a single mod. 

Thus we would assign this bug a severity of medium.

**Comment by dominopizzaaaa** [comment] 2024-11-09 06:05
guys isnt this adding a feature already? should we put this as limitation in UG?

**Comment by izruff** [comment] 2024-11-10 06:06
> guys isnt this adding a feature already? should we put this as limitation in UG?

Yeah this one we cannot fix in v1.6.

We can put this in DG: Planned Enhancements.

**Comment by izruff** [comment] 2024-11-10 07:52
Note that the feature to filter based on course is a duplicate of #232

**Closed** 2024-11-11 12:09 UTC
Labels: priority.Low
