### ISSUE TITLE
Incorrect help command reference

### ISSUE THREAD

**Issue by hpcman** [AY2425S1-CS2103T-T08-4/tp#142] opened 2024-11-05 22:56 UTC
![Screenshot 2024-11-06 055448](https://github.com/user-attachments/assets/2582e636-713d-413c-b82f-bd9627da6585)
The help command should refer to our user guide which is https://ay2425s1-cs2103t-t08-4.github.io/tp/UserGuide.html

**Comment by izruff** [comment] 2024-11-06 22:29
Duplicate of #101, already resolved

**Closed** 2024-11-06 22:30 UTC
Labels: alpha-bug
