### ISSUE TITLE
Unmark attendance doesn't show error message if date is not found

### ISSUE THREAD

**Issue by hpcman** [AY2425S1-CS2103T-T08-4/tp#140] opened 2024-11-05 22:49 UTC
![Screenshot 2024-11-06 054601](https://github.com/user-attachments/assets/04fcec68-c23d-4c3d-91a9-895fd7e566c7)
The input of <code>unmark 1 d/12/01/2024 13:00</code> doesn't show any response. It should give a response that the program doesn't find the date is marked.

**Comment by izruff** [comment] 2024-11-06 21:03
Duplicate of #109

**Closed** 2024-11-06 22:33 UTC
Labels: alpha-bug
