### ISSUE TITLE
[PE-D][Tester E] Attendance parameter in mark command differs from UG specification

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T08-4/tp#205] opened 2024-11-08 16:43 UTC
The user guide states that the Attendance parameter of `mark` command is `case sensitive`, however that is **not** the case.

![image.png](https://raw.githubusercontent.com/tanwartushar/ped/main/files/9e8010cf-ac3b-41ed-9d7f-02d8769ecccb.png)

For instance, the command
`mark 1 d/20/02/2025 08:00 m/absent`
works the same as 
`mark 1 d/20/02/2025 08:00 m/Absent`

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: tanwartushar/ped#4

**Comment by juancarlovieri** [comment] 2024-11-09 06:16
@izruff can you help rectify the Ug for this

**Comment by izruff** [comment] 2024-11-10 08:00
Duplicate of #256

**Closed** 2024-11-11 12:29 UTC
Labels: priority.Medium
